[package]
name = "queue-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
dotenvy = "0.15.7"
tokio = { version = "1.46.1", features = ["full"] }
sea-orm = { version = "1.1.14", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"] }
